#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# compton -f &
picom &

nitrogen --restore &

# tint2 &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

/usr/lib/xfce4/notifyd/xfce4-notifyd &

xfsettingsd &

nm-applet &

pgrep -x clipit > /dev/null || clipit &

# pgrep -x redshift-gtk > /dev/null || redshift-gtk &

# xsetroot -cursor_name left_ptr &

xinput set-prop 13 "libinput Tapping Enabled" "1" &

xinput set-prop 13 "libinput Natural Scrolling Enabled" "1" &

~/.config/polybar/launch.sh &

# polybar example &

# pgrep -x volumeicon > /dev/null || volumeicon &

# pgrep -x xfce4-power-manager > /dev/null || xfce4-power-manager &

# Start Chrome on startup
# sleep 3; pgrep -x chrome > /dev/null || google-chrome &


# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 一 二 三 四 五 六 七 八 九 十


bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config pointer_follows_focus true
# bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a Tint2conf state=floating focus=on

bspc rule -a Nitrogen state=floating

bspc rule -a Google-chrome desktop='^1'

bspc rule -a Plank manage=on

# Google Hangouts
bspc rule -a *:crx_nckgahadagoaajjgafhacjanaoiihapd desktop='^2'

# Google Chats
bspc rule -a *:crx_mdpkiolbdkhdjpekfbkbmhigcaggjagi desktop='^2'

# bspc rule -a Gnome-terminal desktop='^3'
bspc rule -a Gedit desktop='^4'
bspc rule -a Firefox desktop='^5'
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

